version: "3.8"
services:
  db:
    image: postgres:latest
    env_file: ./.env #Here we are using the already existing .env.local file
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "54032:5432"
    networks:
      - extern
volumes:
  data:
networks:
  extern:
    external: true
